language: python
python:
  - "2.7"
# command to install dependencies
install:  pip install ansible==1.9.6
# command to run tests
script:
  - ansible-playbook -i tests/inventory tests/main.yml --syntax-check