---

#### Defensive Programming
# https://github.com/openshift/openshift-ansible/blob/master/docs/best_practices_guide.adoc

- name: Fail for Missing Red Hat Network Username
  fail: msg="This role requires rhn_username to be set and non empty. Set it at the playbook level."
  when: rhn_username is not defined or rhn_username == ''

- name: Fail for Missing Red Hat Network Password
  fail: msg="This role requires rhn_username to be set and non empty. Set it at the playbook level."
  when: rhn_username is not defined or rhn_password == ''

#### Set Facts
# TODO: These probably should be expanded and the vars reduced
- name: Set JBoss EAP Artifact Facts
  set_fact:
    eap_artifact_url: "{{ eap_artifact_repo + '/' + eap_artifact_name }}"
    eap_artifact_dl_dest: "{{ '/tmp/' + eap_artifact_name }}"

- name: Debug JBoss EAP Artifact URL
  debug:
    msg: "{{ eap_artifact_url }}"

- name: Debug JBoss EAP Download Destination
  debug:
    msg: "{{ eap_artifact_dl_dest }}"


#### Create Service Account

- include: jboss_service.yml

#### Download and unzip libraries

- name: Download JBoss EAP from Red Hat Customer Portal
  get_url:
    url: "{{ eap_artifact_url }}"
    dest: "{{ eap_artifact_dl_dest }}"
    url_username: "{{ rhn_username }}"
    url_password: "{{ rhn_password }}"

- name: Extract JBoss EAP Libraries
  sudo: true
  unarchive:
    src: "{{ eap_artifact_dl_dest }}"
    dest: "{{ eap_library_dest }}"
    creates: jboss-eap-6.4
    copy: no
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"


#### Set Sensible Defaults For Runtime

- name: Set Web Bind Address
  lineinfile:
    dest: "{{ eap_runtime_conf_file }}"
    line: JAVA_OPTS="$JAVA_OPTS -Djboss.bind.address=0.0.0.0"
  when: eap_bind_web_interface

- name: Set Management Bind Address
  lineinfile:
    dest: "{{ eap_runtime_conf_file }}"
    line: JAVA_OPTS="$JAVA_OPTS -Djboss.bind.address.management=0.0.0.0"
  when: eap_bind_management_interface

- name: Set User Time Zone for Logs
  lineinfile:
    dest: "{{ eap_runtime_conf_file }}"
    line: "JAVA_OPTS=\"$JAVA_OPTS -Duser.timezone={{eap_logging_timezone}}\""


### Fire it up

- name: Start and Enable jboss-as Service
  service:
    name: jboss-as-standalone.service
    state: started
    enabled: yes
